CREATE DATABASE IF NOT EXISTS practical_db;
USE practical_db;

CREATE TABLE IF NOT EXISTS common_passwords (
  password VARCHAR(255) PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS `2400710` (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);