sonar.projectKey=practical-node-sql-app
sonar.projectName=practical-node-sql-app
sonar.projectVersion=1.0

sonar.sources=.
sonar.exclusions=node_modules/**,tests/**,.scannerwork/**

sonar.sourceEncoding=UTF-8